insert into product_category (id, name) values (1, 'BEBIDAS') on conflict do nothing;
insert into product_category (id, name) values (2, 'ENTRADAS') on conflict do nothing;
insert into product_category (id, name) values (3, 'SALADAS') on conflict do nothing;
insert into product_category (id, name) values (4, 'SOBREMESAS') on conflict do nothing;
insert into product_category (id, name) values (5, 'PRATOS_PRINCIPAIS') on conflict do nothing;
insert into product_category (id, name) values (6, 'MOLHOS') on conflict do nothing;
insert into product_category (id, name) values (7, 'PRATOS_FRIOS') on conflict do nothing;
insert into product_category (id, name) values (8, 'MASSAS') on conflict do nothing;
insert into product_category (id, name) values (9, 'APERITIVOS') on conflict do nothing;