insert into product_category (id, name) values (1, 'BEBIDAS');
insert into product_category (id, name) values (2, 'ENTRADAS');
insert into product_category (id, name) values (3, 'SALADAS');
insert into product_category (id, name) values (4, 'SOBREMESAS');
insert into product_category (id, name) values (5, 'PRATOS_PRINCIPAIS');
insert into product_category (id, name) values (6, 'MOLHOS');
insert into product_category (id, name) values (7, 'PRATOS_FRIOS');
insert into product_category (id, name) values (8, 'MASSAS');
insert into product_category (id, name) values (9, 'APERITIVOS');